name: meson

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  # Customize the meson build type here (release, debug, debugoptimized, etc.)
  BUILD_TYPE: release

jobs:
  build:
    runs-on: debian-latest

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      # Configure CMake in a 'build' subdirectory. `CMAKE_BUILD_TYPE` is only required if you are using a single-configuration generator such as make.
      # See https://cmake.org/cmake/help/latest/variable/CMAKE_BUILD_TYPE.html?highlight=cmake_build_type
      run: meson setup ${{github.workspace}}/build . --buildtype=${{env.BUILD_TYPE}}

    - name: Build
      # Build your program with the given configuration
      run: meson compile -C ${{github.workspace}}/build
